### ISSUE TITLE
execution reverted: TransferHelper: TRANSFER_FROM_FAILED

### ISSUE THREAD

**Issue by Axxoul** [vincor1986/vSwap#1]
Hi, 

Great work on this script, very helpful. 

However all transactions fail with "execution reverted: TransferHelper: TRANSFER_FROM_FAILED"

Do we not need to approve tokens before being able to use them?

**Comment by vincor1986** [comment]
The contract does need to be approved to spend the token first. The contract should be approved as the "spender" for the token being traded (the first token in the "path" array). 

It is failing during the "safeTransferFrom" operation. Are you able to provide an example of the data you are sending as the parameters, or the code you are using to generate the parameters?

**Comment by Axxoul** [comment]
Just copy / pasted the contract as is (from vSwap.sol) and deployed it to BSC mainnet.

Then tried with the following params:

**amountIn:** 100000000000000000
**amountOutMin:** 50000000000000000 // (just to test the whole swap, since I know I will loose money)
**path:** ["0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c","0xe9e7cea3dedca5984780bafc599bd69add087d56","0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c"] // WBNB > BUSD > WBNB
**pairPath:** ["0x58f876857a02d6762e0101bb5c46a8c1ed44dc16","0x58f876857a02d6762e0101bb5c46a8c1ed44dc16"] // PancakeSwap WBNB-BUSD pool
**fee:** [20,20]
**to:** 0x******** // my_wallet_addr 
**deadline:** 1649517012

**Comment by vincor1986** [comment]
Thanks for the info.

I can see one thing that might be causing the problem. The pancake swap fees changed when pancake swap went from v1 to v2. The v1 fee was 0.2% but the v2 fee is 0.25%. As both of the LPs in the pairPath are v2 pools, the "fee" array should be: [25,25].

That might resolve the problem. Try it out and please let me know how it goes.
